[package]
name = "rami"
version = "0.1.0"
authors = ["coord.e <me@coord-e.com>"]
build = "build.rs"

[[example]]
name = "client"
path = "examples/client/client.rs"

[dependencies]
futures = "0.1.23"
protobuf = "2.0.4"
grpcio = "0.3"

[build-dependencies]
protoc-grpcio = "0.2.0"
