version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Enable the experimental feature of Docker CLI
          command: |
            mkdir -p ~/.docker
            echo '{"experimental": "enabled"}' > ~/.docker/config.json
      - run:
          name: Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build image
          command: |
            docker build -t peripherio/peripherio:amd64 --build-arg CARGO_TARGET=x86_64-unknown-linux-musl --build-arg TARGET_TAG=x86_64-musl --build-arg ALPINE_DIGEST=sha256:02892826401a9d18f0ea01f8a2f35d328ef039db4e1edcc45c630314a0457d5b .
            docker build -t peripherio/peripherio:armhf --build-arg CARGO_TARGET=arm-unknown-linux-musleabihf --build-arg TARGET_TAG=arm-musleabihf --build-arg ALPINE_DIGEST=sha256:acc1c7fcb0bcd59a2becdc3342204d30c0aa1009b3a2bd954536338acfe0bded .
      - run:
          name: Push the image
          command: |
            docker push peripherio/peripherio:amd64
            docker push peripherio/peripherio:armhf
      - run:
          name: Create manifest
          command: |
            docker manifest create \
              peripherio/peripherio:latest \
              peripherio/peripherio:armhf \
              peripherio/peripherio:amd64
            docker manifest annotate --os linux --arch arm --variant v8 peripherio/peripherio:latest peripherio/peripherio:armhf
            docker manifest annotate --os linux --arch amd64 peripherio/peripherio:latest peripherio/peripherio:amd64
      - run:
          name: Push the manifest
          command: |
            docker manifest push peripherio/peripherio:latest
