version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build image
          command: |
            docker build -t peripherio/peripherio:x86_64 --build-arg CARGO_TARGET=x86_64-unknown-linux-musl --build-arg TARGET_TAG=x86_64-musl .
            docker build -t peripherio/peripherio:armhf --build-arg CARGO_TARGET=armv7-unknown-linux-musleabihf --build-arg TARGET_TAG=arm-musleabihf .
      - run:
          name: Push the image
          command: |
            docker push peripherio/peripherio:x86_64
            docker push peripherio/peripherio:armhf
      - run:
          name: Create manifest
          command: |
            docker manifest create \
              peripherio/peripherio:latest \
              peripherio/peripherio:armhf \
              peripherio/peripherio:x86_64
            docker manifest annotate --os linux --arch arm --variant v8 peripherio/peripherio:latest peripherio/peripherio:armhf
            docker manifest annotate --os linux --arch x86_64 peripherio/peripherio:latest peripherio/peripherio:x86_64
      - run:
          name: Push the manifest
          command: |
            docker manifest push peripherio/peripherio:latest
