version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Enable the experimental feature of Docker CLI
          command: |
            mkdir -p ~/.docker
            echo '{"experimental": "enabled"}' > ~/.docker/config.json
      - run:
          name: Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build image
          command: |
            docker build -t peripherio/peripherio:amd64 --build-arg CARGO_TARGET=x86_64-unknown-linux-gnu --build-arg TARGET_TAG=x86 --build-arg BASE_DIGEST=sha256:a8c1702fe60da76824a7604ae3a3f1db29262b9099d3a759e169a90cb90ef9e3 .
            docker build -t peripherio/peripherio:armhf --build-arg CARGO_TARGET=arm-unknown-linux-gnueabihf --build-arg TARGET_TAG=arm --build-arg BASE_DIGEST=sha256:98f3a3dae86e8a8cd87f1166d5464659c6eb0eceff295579ffde6b603c708e7e .
      - run:
          name: Push the image
          command: |
            docker push peripherio/peripherio:amd64
            docker push peripherio/peripherio:armhf
      - run:
          name: Create manifest
          command: |
            docker manifest create \
              peripherio/peripherio:latest \
              peripherio/peripherio:armhf \
              peripherio/peripherio:amd64
            docker manifest annotate --os linux --arch arm --variant v7 peripherio/peripherio:latest peripherio/peripherio:armhf
            docker manifest annotate --os linux --arch amd64 peripherio/peripherio:latest peripherio/peripherio:amd64
      - run:
          name: Push the manifest
          command: |
            docker manifest push peripherio/peripherio:latest
