version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build image
          command: |
            docker build -t peripherio/peripherio:arm --build-arg TARGET=armv7-unknown-linux-musleabihf .
            docker build -t peripherio/peripherio:x86 --build-arg TARGET=x86_64-unknown-linux-musl .
      - run:
          name: Create manifest
          command: |
            docker manifest create \
              peripherio/peripherio:latest \
              peripherio/peripherio:linux \
              peripherio/peripherio:arm
      - run:
          name: Push
          command: |
            docker manifest push peripherio/peripherio:latest
